#input არის ის რაც შედის კომპიუტერში მხოლო output კი რაც გამოდის კომპიუტერიდან
user_name = input("what is your name ")
print("hi "+user_name)
print("    ^")
print("    |")
print("რასაც წერ ის შედის კომპიუტერში ანუ input-ი ეწოდება მაგრამ ტერმინაში  გამოდის მას output-ი ეწოდება")
print(                                   )
user=input("hi ")
user=input('what is you name my friend ')
user=input('hi '+user)
print(                                                        )
name=input('რა გქვია ')
print('გამარჯობა '+ name)
surname=input('რა გვარიხარ ')
print('გამარჯობა ' + name  + surname)
print(             )
name=input('hi whats is your name ')
surrname=input(' whats your surname ')
city=input('were you live')
print(             )

