name=input("write your name :")
print(name.upper()) 
print(               )
name=input("write your name :")
name_LOWER = name.lower()
print(name_LOWER)
print(                                     )
name=input("write your name :")
print(name.title())
print(                   )
name=input("write your name :")
print(name.replace("a", "o"))
print(                           )
name=input("write your name :")
if name.isupper():
    print("string is uppercase")
else:
    print("string is lowercase")
print(                 )
name=input("write your name :")
if name.islower():
    print("string is lowercase")
else:
    print("string is uppercase")
print(                                      )
name=input("write your name :")
print(name.count(2)) 
print(                           )
name=input("write your name :")
print(name.strip())
print(                                     )
name=input("write your name :")
print(name.lstrip())
print(                         )
name=input("write your name :")
print(name.rstrip())
print(           )
name=input("write your name :")
