user_year = int(input("Enter your birth year: "))
age = 2025 - user_year
print("I'm " + str(age) + " and I was born in " + str(user_year))
print(                                                             )
user_number= int(input("Enter any number: "))
print (int(user_number) + int(user_number))
print (int(user_number) - int(user_number))
print (int(user_number) * int(user_number))
print (int(user_number) / int(user_number))
print (int(user_number) ** int(user_number))
print (int(user_number) // int(user_number))
print(                                          )
calculator= int(input("Enter any number: "))
calculator2= int(input("Enter any number again: "))
calculator3= int(input("Enter number agan pls: "))
print(int(calculator)-int(calculator2)*int(calculator3))
print(                                 )
# Ask the user for their name, age, and birth year
name = input("Enter your name: ")
age = int(input("Enter your age: "))
year = int(input("Enter your birth year: "))
